# Copyright 2017 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
swagger: "2.0"
info:
  title: "Airport Codes"
  description: "Get the name of an airport from its three-letter IATA code."
  version: "1.0.0"
# This field will be replaced by the deploy_api.sh script.
host: "YOUR-PROJECT-ID.appspot.com"
schemes:
  - "https"
paths:
  "/getDeptWithMaxSiteVisits":
    get:
      description: "Gets the department who had maximum site visits yesterday for a date (Aug-7)"
      operationId: "visitDate"
      parameters:
        -
          name: visitDate
          in: query
          required: true
          type: string
      responses:
        200:
          description: "Success."
          schema:
            type: string
        400:
          description: "The site visit date is invalid or missing."
  "/getDeptWithMaxOrders":
    get:
      description: "Gets the department who had maximum orders yesterday for a date (Aug-7)"
      operationId: "visitDate"
      parameters:
        -
          name: visitDate
          in: query
          required: true
          type: string
      responses:
        200:
          description: "Success."
          schema:
            type: string
        400:
          description: "The site visit date is invalid or missing."  
  "/getDeptWithMaxConversion":
    get:
      description: "Gets the department who had maximum conversion yesterday for a date (Aug-7)"
      operationId: "visitDate"
      parameters:
        -
          name: visitDate
          in: query
          required: true
          type: string
      responses:
        200:
          description: "Success."
          schema:
            type: string
        400:
          description: "The site visit date is invalid or missing."                    
  "/getDeptWithMaxGD":
    get:
      description: "Gets the department who had maximum GD yesterday for a date (Aug-7)"
      operationId: "visitDate"
      parameters:
        -
          name: visitDate
          in: query
          required: true
          type: string
      responses:
        200:
          description: "Success."
          schema:
            type: string
        400:
          description: "The site visit date is invalid or missing."            
  "/getMCWithMaxVisits":
    get:
      description: "Gets the Marketing Channel who had maximum visits yesterday for a date (Aug-7)"
      operationId: "visitDate"
      parameters:
        -
          name: visitDate
          in: query
          required: true
          type: string
      responses:
        200:
          description: "Success."
          schema:
            type: string
        400:
          description: "The site visit date is invalid or missing."            
  "/getTop10ProductsWithMaxGD":
    get:
      description: "Gets the Top 10 products who had maximum GD yesterday for a date (Aug-7)"
      operationId: "visitDate"
      parameters:
        -
          name: visitDate
          in: query
          required: true
          type: string
      responses:
        200:
          description: "Success."
          schema:
            type: string
        400:
          description: "The site visit date is invalid or missing."            
  "/getMCWithMaxGD":
    get:
      description: "Gets the Marketing Channel who had maximum GD yesterday for a date (Aug-7)"
      operationId: "visitDate"
      parameters:
        -
          name: visitDate
          in: query
          required: true
          type: string
      responses:
        200:
          description: "Success."
          schema:
            type: string
        400:
          description: "The site visit date is invalid or missing."         
  "/getSpecialBuy":
    get:
      description: "Gets today's special buy"
      responses:
        200:
          description: "Success."
          schema:
            type: string
  "/getNoOfSKUsSpecialBuy":
    get:
      description: "Gets number of SKUs in today's special buy"
      responses:
        200:
          description: "Success."
          schema:
            type: string
  "/getTodaysConv":
    get:
      description: "Gets the today's conversion as of specified time"
      operationId: "time"
      parameters:
        -
          name: time
          in: query
          required: true
          type: string
      responses:
        200:
          description: "Success."
          schema:
            type: string
        400:
          description: "The time is invalid or missing."   
  "/getMCWithMaxConv":
    get:
      description: "Gets the Marketing Channel with max conversion as of specified time"
      operationId: "time"
      parameters:
        -
          name: time
          in: query
          required: true
          type: string
      responses:
        200:
          description: "Success."
          schema:
            type: string
        400:
          description: "The time is invalid or missing."   